#Max is 1, everything above 0.7 is kinda laggy
max-fly-speed: 0.7
#Multiplier how much the speed increases/decreases per slot change
speed-multiplyer: 0.05
#If true the players can get slower than the default fly speed (could be useful for some montages or something)
below-default: false
#The scroll direction to get faster ("left" or "right")
direction: "left"

#The fly speed command settings
command:
  name: "flyspeed"
  description: "Change a players fly speed"
  usage: "/flyspeed <float: speed> [string: player]"
  aliases: ["fs"]
  permission:
    self: "flyspeed.command.self"
    other: "flyspeed.command.other"
  success: "§aYou have successfully set the flyspeed of§b {target}§a to§6 {speed}§a!"
  error: "§b{target}§c is not in spectator!"
